name: navedge
description: "A Flutter app with a C++ backend for multi-constraint route optimization."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core State Management
  provider: ^6.1.4

  # Persistent Storage
  shared_preferences: ^2.2.2

  # UI Enhancements
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  flutter_animate: ^4.3.0
  lottie: ^1.4.3
  flutter_gradient_colors: ^2.0.0
  carousel_slider: ^5.0.0
  flutter_switch: ^0.3.2
  font_awesome_flutter: ^10.8.0
  flutter_spinkit: ^5.2.1

  # Routing
  go_router: ^15.0.0

  # Maps & Location
  latlong2: ^0.9.0
  geolocator: ^14.0.0
  geocoding: ^3.0.0

  # Autocomplete / Place Search
  flutter_typeahead: ^5.2.0

  # Network & HTTP
  http: ^1.3.0
  dio: ^5.8.0+1

  # Permissions & Connectivity
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.3

  # Audio & Haptics
  audioplayers: ^6.4.0
  just_audio: ^0.10.0
  vibration: ^3.1.3
  flutter_vibrate: ^1.3.0

  # Utilities
  url_launcher: ^6.2.5
  intl: ^0.19.0
  collection: ^1.18.0
  path_provider: ^2.1.2
  logger: ^2.1.0

  # JSON serialization

  # New / Feature Enhancements
  loading_indicator: ^3.1.0
  google_places_flutter: ^2.1.0
  flutter_animated_icons: ^1.0.1
  rive: ^0.13.20
  adaptive_dialog: ^2.4.1
  animate_do: ^4.2.0
  animations: ^2.0.11
  appkit_ui_element_colors: ^1.0.0
  cross_file: ^0.3.4+2
  csslib: ^1.0.2
  dart_earcut: ^1.2.0
  diacritic: ^0.1.6
  dynamic_color: ^1.7.0
  email_validator: ^3.0.0
  equatable: ^2.0.7
  file_selector_linux: ^0.9.3+2
  file_selector_macos: ^0.9.4+2
  file_selector_platform_interface: ^2.6.2
  file_selector_windows: ^0.9.3+4
  firebase_core: ^3.13.0
  firebase_core_platform_interface: ^5.4.0
  firebase_core_web: ^2.22.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.27
  flutter_sound: ^9.28.0
  flutter_sound_platform_interface: ^9.28.0
  flutter_sound_web: ^9.28.0
  google_maps: ^8.1.1
  google_maps_flutter: ^2.12.1
  google_maps_flutter_android: ^2.16.0
  google_maps_flutter_ios: ^2.15.0
  google_maps_flutter_platform_interface: ^2.11.1
  google_maps_flutter_web: ^0.5.12
  gradient_borders: ^1.0.1
  html: ^0.15.5
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+22
  image_picker_for_web: ^3.0.6
  image_picker_ios: ^0.8.12+2
  image_picker_linux: ^0.2.1+2
  image_picker_macos: ^0.2.1+2
  image_picker_platform_interface: ^2.10.1
  image_picker_windows: ^0.2.1+1
  intersperse: ^2.0.0
  macos_ui: ^2.1.10
  macos_window_utils: ^1.7.1
  package_info_plus: ^8.3.0
  package_info_plus_platform_interface: ^3.2.0
  phone_input: ^1.0.0
  process_run: ^1.2.4
  sanitize_html: ^2.1.0
  sentry: ^8.14.1
  shimmer: ^3.0.0
  sprintf: ^7.0.0
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.3.4
  webview_flutter_platform_interface: ^2.10.0
  webview_flutter_wkwebview: ^3.18.5
  speech_to_text: ^7.0.0
  shared_preferences_android: ^2.4.9
  url_launcher_ios: ^6.3.3
  permission_handler_apple: ^9.4.7
  flutter_rating_bar: ^4.0.1
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  badges: ^3.1.2
  firebase_storage: ^12.4.5
  emoji_picker_flutter: ^4.3.0
  loading_animation_widget: ^1.3.0
  sign_in_with_apple: ^7.0.1
  cloud_firestore: ^5.6.6
  screen_brightness: ^2.1.2
  routing_client_dart: ^1.0.7
  flutter_polyline_points: ^2.1.0
  animated_widgets: ^1.1.0
  flutter_haptic: ^0.0.3
  sentry_flutter: ^8.14.1
  json_annotation: ^4.8.0
  json_serializable: ^6.7.1
  cached_network_image: ^3.4.1
  share_plus: ^11.0.0
  another_flushbar: ^1.12.30
  flutter_inappwebview: ^6.1.5
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7

dependency_overrides:
  flutter_vibrate:
    path: local_plugins/flutter_vibrate
  flutter_haptic:
    path: local_plugins/flutter_haptic

flutter:
  uses-material-design: true

  assets:
    - assets/route.json
    - assets/api/.env
    - assets/fonts/
    - assets/images/gradient_bg.png

    # Sounds
    - assets/sounds/notifications/new_message.mp3
    - assets/sounds/notifications/success.mp3
    - assets/sounds/notifications/error.mp3
    - assets/sounds/notifications/warning.mp3
    - assets/sounds/ui_sounds/button_click.mp3
    - assets/sounds/ui_sounds/navigation_tap.mp3
    - assets/sounds/ui_sounds/swipe.mp3
    - assets/sounds/ui_sounds/back_press.mp3
    - assets/sounds/ui_sounds/pop.mp3
    - assets/sounds/ui_sounds/confirm.mp3
    - assets/sounds/ui_sounds/button_click.mp3
    - assets/sounds/ui_sounds/hover.mp3
    - assets/sounds/chatbot/chatbot_response.mp3
    - assets/sounds/chatbot/chatbot_typing.mp3
    - assets/sounds/chatbot/chatbot_welcome.mp3
    - assets/sounds/maps/navigation_start.mp3
    - assets/sounds/maps/reroute_alert.mp3
    - assets/sounds/maps/location_pin_drop.mp3

    # Images - App Logos
    - assets/images/app_logo/logo.png

    # Icons
    - assets/images/icons/home.png
    - assets/images/icons/settings.png
    - assets/images/icons/chatbot.png
    - assets/images/icons/gps.png
    - assets/images/icons/back_arrow.png
    - assets/images/icons/forward_arrow.png
    - assets/images/icons/search.png
    - assets/images/icons/location_pin.png
    - assets/images/icons/login.png
    - assets/images/icons/profile.jpg
    - assets/images/icons/google_logo.jpeg
    - assets/images/icons/github_logo.png
    - assets/images/icons/microsoft_logo.png
    - assets/images/icons/about.jpeg
    - assets/images/icons/help.jpeg
    - assets/images/icons/car.png
    - assets/images/icons/walk.png
    - assets/images/icons/bike.png
    - assets/images/icons/bus.png
    - assets/images/icons/train.png
    - assets/images/icons/other.png
    - assets/images/social/facebook.png
    - assets/images/social/twitter.png
    - assets/images/social/linkedin.png
    - assets/images/social/github.png

    # Backgrounds
    - assets/images/backgrounds/main_bg.png
    - assets/images/backgrounds/chat_bg.png
    - assets/images/backgrounds/dark_theme_bg.png
    - assets/images/backgrounds/main.jpg
    - assets/images/backgrounds/dark.jpg

    # Map Elements
    - assets/images/maps/marker.png
    - assets/images/maps/route_start.png
    - assets/images/maps/route_end.png
    - assets/images/maps/traffic_layer.png
    - assets/images/maps/satellite_view.png

    # Chatbot
    - assets/images/chatbot/chatbot_avatar.png
    - assets/images/chatbot/chatbot_typing.gif

    # Animations
    - assets/animations/world.json
    - assets/animations/fireworks.json
    - assets/animations/welcome.json
    - assets/animations/loading_map.json
    - assets/animations/a_star.json
    - assets/animations/floyd_warshall.json
    - assets/animations/bellman_ford.json
    - assets/animations/dijkstra.json
    - assets/images/animations/loading.json
    - assets/images/animations/route_finding.json
    - assets/images/animations/chatbot_typing.json
    - assets/images/animations/mic_wave.json
    - assets/images/animations/login_success.json
    - assets/images/animations/login_failed.json
    - assets/images/animations/day_loop.json
    - assets/images/animations/night_loop.json
    - assets/images/animations/robot_hello.json
    - assets/animations/location_loading.json
    - assets/animations/loading_dots.json
    - assets/lottie/chatbot_interaction.json
    - assets/lottie/dark_mode.json
    - assets/lottie/location_permission.json
    - assets/lottie/offline_map.json
    - assets/lottie/route_planning.json
    - assets/lottie/login_security.json

    # Profile
    - assets/images/user_profiles/default_male.png
    - assets/images/user_profiles/default_female.png
    - assets/images/user_profiles/default_robot.png
    - assets/images/default_profile.png

    # Buttons
    - assets/images/buttons/primary_button.png
    - assets/images/buttons/secondary_button.png
    - assets/images/buttons/pressed_button.png

    # Placeholders
    - assets/images/placeholders/no_image_available.png
    - assets/images/placeholders/no_connection.png

    # Badges
    - assets/images/badges/gold_badge.png
    - assets/images/badges/silver_badge.png
    - assets/images/badges/bronze_badge.png
    - assets/images/badges/basic_badge.png

  fonts:
  
    - family: NotoEmoji
      fonts:
        - asset: assets/fonts/NotoEmoji-Regular.ttf
        - asset: assets/fonts/NotoEmoji-Bold.ttf
          weight: 700

    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic

    - family: NotoSansSymbols
      fonts:
        - asset: assets/fonts/NotoSansSymbols-Regular.ttf
        - asset: assets/fonts/NotoSansSymbols2-Regular.ttf

    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
        - asset: assets/fonts/NotoSerif-Bold.ttf
          weight: 700

    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf

    - family: NotoSansDevanagari
      fonts:
        - asset: assets/fonts/NotoSansDevanagari-Regular.ttf

    - family: NotoSansHebrew
      fonts:
        - asset: assets/fonts/NotoSansHebrew-Regular.ttf

    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf

    - family: NotoSansCJK
      fonts:
        - asset: assets/fonts/NotoSansCJK-Regular.ttc

    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf

    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf

    - family: NotoSansTC
      fonts:
        - asset: assets/fonts/NotoSansTC-Regular.otf

    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf

    - family: Roboto
      fonts:
        - asset: assets/fonts/static/Roboto-Regular.ttf
        - asset: assets/fonts/static/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/static/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/static/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/static/Roboto-Medium.ttf
          weight: 500
