// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBneCT-Z5CTjJbcHvm--dK-sA-Z1EK0JRg',
    appId: '1:1077383823236:web:4b2ebfd8d13844866be7d1',
    messagingSenderId: '1077383823236',
    projectId: 'navedge-2480',
    authDomain: 'navedge-2480.firebaseapp.com',
    databaseURL: 'https://navedge-2480-default-rtdb.firebaseio.com',
    storageBucket: 'navedge-2480.appspot.com',
    measurementId: 'G-H9G0QB2NCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-uQHDCX-r1JHHwGJKZKB_qpJMYLFIw6g',
    appId: '1:1077383823236:android:dc50536f0e4076d16be7d1',
    messagingSenderId: '1077383823236',
    projectId: 'navedge-2480',
    databaseURL: 'https://navedge-2480-default-rtdb.firebaseio.com',
    storageBucket: 'navedge-2480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4kQZpRvPSQcvzzYBmJOhv4EEJpvPgqGM',
    appId: '1:1077383823236:ios:ca312532b241f8596be7d1',
    messagingSenderId: '1077383823236',
    projectId: 'navedge-2480',
    databaseURL: 'https://navedge-2480-default-rtdb.firebaseio.com',
    storageBucket: 'navedge-2480.appspot.com',
    iosClientId: '1077383823236-0uuq2kd4q2e6piuhucprsdcfkest7qlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.navedge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4kQZpRvPSQcvzzYBmJOhv4EEJpvPgqGM',
    appId: '1:1077383823236:ios:ca312532b241f8596be7d1',
    messagingSenderId: '1077383823236',
    projectId: 'navedge-2480',
    databaseURL: 'https://navedge-2480-default-rtdb.firebaseio.com',
    storageBucket: 'navedge-2480.appspot.com',
    iosClientId: '1077383823236-0uuq2kd4q2e6piuhucprsdcfkest7qlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.navedge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBneCT-Z5CTjJbcHvm--dK-sA-Z1EK0JRg',
    appId: '1:1077383823236:web:50146ac376914ecf6be7d1',
    messagingSenderId: '1077383823236',
    projectId: 'navedge-2480',
    authDomain: 'navedge-2480.firebaseapp.com',
    databaseURL: 'https://navedge-2480-default-rtdb.firebaseio.com',
    storageBucket: 'navedge-2480.appspot.com',
    measurementId: 'G-MKJ39XHT3E',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBneCT-Z5CTjJbcHvm--dK-sA-Z1EK0JRg',
    appId: '1:1077383823236:web:50146ac376914ecf6be7d1',
    messagingSenderId: '1077383823236',
    projectId: 'navedge-2480',
    authDomain: 'navedge-2480.firebaseapp.com',
    databaseURL: 'https://navedge-2480-default-rtdb.firebaseio.com',
    storageBucket: 'navedge-2480.appspot.com',
    measurementId: 'G-MKJ39XHT3E',
  );
}

