name: flutter_haptic
description: Flutter Plugin for calling mobile native Haptic feature
version: 0.0.3
repository: https://github.com/creche-studio/flutter_haptic

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: studio.creche.flutter_haptic
        pluginClass: FlutterHapticPlugin
      ios:
        pluginClass: FlutterHapticPlugin
